spring:
  application:
    name: proxyportal
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:h2:mem:portal;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

npm:
  base-url: ${NPM_BASE_URL}
  identity: ${NPM_IDENTITY}
  secret: ${NPM_SECRET}

logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
    com.zaxxer.hikari: DEBUG
