spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/proxyportal}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:proxyportal}
    password: ${SPRING_DATASOURCE_PASSWORD:proxyportal}
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
